name: bilinear_gradient
description: A container that allows you to wrap your widgets within a 4 colors gradient.
version: 0.0.1
homepage: https://github.com/sthefanoss/bilinear-gradient

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

flutter:
  shaders:
    - shaders/bilinear_gradient.frag
